import Searchbar from  '../components/Searchbar'

export const metadata = {
  title: 'd.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Searchbar />
      {children}
    </div>  
  )
}
